# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 04:27


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(db_index=True)),
                ('original_url_hash', models.CharField(max_length=64)),
                ('shortened_url', models.URLField(unique=True)),
                ('backend', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Short url',
                'verbose_name_plural': 'Short urls',
                'ordering': ['-created'],
                'get_latest_by': 'created',
            },
        ),
        migrations.AlterUniqueTogether(
            name='shorturl',
            unique_together=set([('original_url_hash', 'backend')]),
        ),
    ]
